# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
keybinding:
  universal:
    pushFiles: <c-p>
    createPatchOptionsMenu: P
gui:
  nerdFontsVersion: "3"
  showCommandLog: false
  showBottomLine: false
  showDivergenceFromBaseBranch: arrowAndNumber
  border: single
  spinner:
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"
git:
  parseEmoji: true
  paging:
    colorArg: always
    # https://github.com/jesseduffield/lazygit/issues/3473#issuecomment-2039010947
    pager: delta --paging=never --dark
  # delta not support `git log --graph`
  # https://github.com/jesseduffield/lazygit/blob/v0.28.2/docs/Config.md#default
  # https://github.com/dandavison/delta/issues/141
  branchLogCmd: "git log --abbrev-commit --pretty=medium {{branchName}} --"
  overrideGpg: true
  allBranchesLogCmds:
    - git log --all --abbrev-commit --pretty=medium
disableStartupPopups: false
customCommands:
  - key: "c"
    command: "git browse-ci"
    context: "status"
    description: "Open CI page"
    loadingText: "Opening CI page..."
  - key: "n"
    context: "localBranches"
    prompts:
      - type: "menu"
        title: "What kind of branch is it?"
        key: "BranchType"
        options:
          - name: "feature"
            description: "branch based off develop for new feature"
            value: "feature"
          - name: "bugfix"
            description: "branch based off develop for minor bug fixes"
            value: "bugfix"
          - name: "release"
            description: "branch based off develop for release prepare"
            value: "release"
          - name: "hotfix"
            description: "branch based off main for critical bug fixes"
            value: "hotfix"
          - name: "misc"
            description: "branch for misc"
            value: "misc"
      - type: "input"
        title: "What is the new branch name?"
        key: "BranchName"
        initialValue: ""
    command: "git checkout -b {{.Form.BranchType}}/{{.Form.BranchName}}"
    loadingText: "Creating branch"
  - key: "f"
    command: "yazi"
    context: "status"
    description: "Open file manager"
    output: terminal
  - key: "i"
    command: "git open --issue"
    context: "status"
    description: "Open issue page"
    loadingText: "Opening issue page..."
  - key: "o"
    command: "git open"
    context: "status"
    description: "Open repository page"
    loadingText: "Opening repository page..."
  - key: "c"
    command: "git czg"
    context: "files"
    description: "Commit changes with git cz"
    output: terminal
  - key: "w"
    command: "git cz --no-verify"
    context: "files"
    description: "Commit changes with git cz --no-verify"
    output: terminal
  - key: "<c-f>"
    command: "yazi {{.SelectedFile.Name}}"
    context: "files"
    description: "Open file manager"
    output: terminal
  - key: "D"
    # yamllint disable-line rule:line-length
    command: "git delete-merged-branches"
    context: "localBranches"
    description: "Prune local branches that have been merged to default branch"
    loadingText: "Pruning..."
    prompts:
      - type: "confirm"
        title: "Prune local branches"
        body: "Are you sure you want to prune local branches?"
  - key: "D"
    command: "git remote prune {{.SelectedRemote.Name}}"
    context: "remotes"
    description: "Prune deleted remote branches"
    loadingText: "Pruning..."
    prompts:
      - type: "confirm"
        title: "Prune deleted remote branches"
        body: "Are you sure you want to prune deleted remote branches?"
  # https://github.com/jesseduffield/lazygit/issues/1807
  - key: "<c-t>"
    command: "git revert --continue"
    context: "commits"
    description: "Continue the revert operation in progress"
    output: terminal
# NOTE: self-hosted GitLab configuration for work
# services:
#   'example.com': 'gitlab:example.com'
