general:
  startup_commands: ['shell-exec %userprofile%/.glzr/glazewm/hotkeys.ahk']
  shutdown_commands: ['shell-exec taskkill /IM AutoHotkey64.exe /F']
  config_reload_commands: []
  focus_follows_cursor: true
  toggle_workspace_on_refocus: false
  cursor_jump:
    enabled: true
    trigger: 'window_focus'
  hide_method: 'cloak'
  show_all_in_taskbar: true

gaps:
  scale_with_dpi: true
  inner_gap: '20px'
  outer_gap:
    top: '20px'
    right: '20px'
    left: '20px'
    bottom: '20px'

window_effects:
  focused_window:
    border:
      enabled: true
      color: '#33ccffee'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: 'square'
    transparency:
      enabled: false
  other_windows:
    border:
      enabled: true
      color: '#595959aa'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: 'square'
    transparency:
      enabled: false

window_behavior:
  initial_state: 'tiling'
  state_defaults:
    floating:
      centered: false
      shown_on_top: true
    fullscreen:
      maximized: false
      shown_on_top: true

workspaces:
  - name: '1'
  - name: '2'
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'

window_rules:
  - commands: ['ignore']
    match:
      - window_process: {equals: 'zebar'}
      - window_title: {regex: '[Pp]icture.in.[Pp]icture'}
        window_class: {regex: 'Chrome_WidgetWin_1|MozillaDialogClass'}
      - window_process: {equals: 'PowerToys'}
        window_class: {regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]'}
      - window_process: {equals: 'PowerToys'}
        window_title: {regex: '.*? - Peek'}
      - window_process: {equals: 'Lively'}
        window_class: {regex: 'HwndWrapper'}
      - window_process: {equals: 'pinentry'}
      - window_process: {equals: 'ueli'}
      - window_title: {equals: 'Microsoft Teams Notification'}
      - window_title: {equals: 'Microsoft Teams Call'}
      - window_title: {regex: 'Meeting compact view .*'}
      - window_process: {equals: 'POWERPNT'}
        window_class: {equals: 'PodiumParent'}
      - window_process: {regex: 'ScreenToGif'}
        window_title: {regex: 'Pre-starting...'}
      - window_process: {regex: 'ScreenToGif'}
        window_title: {regex: 'Discard recording'}
      - window_process: {regex: 'ScreenToGif'}
        window_title: {regex: 'Press F8 to stop the recording'}
      - window_process: {regex: 'ScreenToGif'}
        window_title: {regex: 'Exiting the Editor'}
      - window_process: {equals: 'msrdc'}
