[env]
_.path = ["{{config_root}}/bin"]
GOSS_VARS = "goss-vars.yaml"
NODE_PATH = "{{env.XDG_DATA_HOME}}/mise/installs/npm-commitlint-config-conventional/19.8.0/lib/node_modules"

[tools]
"npm:@commitlint/cli" = "19.8.0"
"npm:@commitlint/config-conventional" = "19.8.0"
