use_nerdfont = true
hide_display_names = true

[keybindings]
"Ctrl+q" = "focus queue"
"Ctrl+w" = "focus search"
"Ctrl+e" = "focus library"
"Ctrl+i" = "focus cover"
"Ctrl+p" = "playpause"
"Ctrl+h" = "back"
"Ctrl+r" = "reload"
"Ctrl+n" = "noop"
"Ctrl+a" = "noop"
# https://github.com/hrkfdn/ncspot/issues/230#issuecomment-683444176
"G" = "move bottom"
"g" = "move top"
"Ctrl+f" = "move pagedown 1.0"
"Ctrl+b" = "move pageup 1.0"

[theme]
background = "black"
primary = "light white"
secondary = "light black"
title = "#7aa2f7"
playing = "#7aa2f7"
playing_selected = "#7dcfff"
playing_bg = "#24283b"
highlight = "#c0caf5"
highlight_bg = "#292e42"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "#7aa2f7"
statusbar_bg = "#7aa2f7"
cmdline = "light white"
cmdline_bg = "black"
search_match = "light red"
