---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: pentest-machine
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}
spec:
  ports:
    - port: {{ .Values.port }}
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
