[settings]
jobs = 20
experimental = true

[settings.npm]
bun = true

[tools]
gotestsum = "latest"
kyverno = "latest"
"pipx:posting" = { version = "2.5.4", uvx_args = "--python 3.12 --prerelease=allow" }
"pipx:harlequin" = { version = "2.1.1", uvx_args = "--python 3.13" }
"go:gotest.tools/gotestsum" = "latest"
"go:github.com/josharian/impl" = "latest"
"go:github.com/fatih/gomodifytags" = "latest"
"go:github.com/rhysd/vim-startuptime" = "latest"
"pipx:litellm" = { version = "1.71.1", extras = "proxy" }
"npm:czg" = "1.11.1"
"npm:gitmoji-cli" = "9.6.0"
"ubi:YiNNx/cmd-wrapped" = "0.4"
