[settings]
jobs = 20
experimental = true

[settings.npm]
bun = true

[tools]
"npm:czg" = "1.11.1"
"npm:gitmoji-cli" = "9.6.0"
"ubi:YiNNx/cmd-wrapped" = "0.4"
dyff = "1.10.1"
jqp = "0.7.0"
lefthook = "1.11.13"
opa = "1.5.0"
"npm:@redocly/cli" = "1.34.3"
"npm:sql-formatter" = "15.6.2"
"npm:git-open" = "3.1.0"
"aqua:knqyf263/pet" = "1.0.1"
"go:github.com/hashicorp/hcl/v2/cmd/hclfmt" = "v2.24.0"

# AI
"npm:opencode-ai" = "0.11.1"
"pipx:mcpo" = "0.0.17"

# app
## go
gotestsum = "1.12.2"
"go:github.com/josharian/impl" = "1.4.0"
"go:github.com/fatih/gomodifytags" = "1.17.0"
golangci-lint = "2.1.6"
"go:github.com/cweill/gotests/..." = "1.6.0"

# infra
## container
hadolint = "2.12.0"
"ubi:docker/docker-credential-helpers" = { version = "0.9.3", exe = "docker-credential-pass" }
## terraform
terraform-docs = "0.20.0"
## kubernetes
kind = "0.29.0"
kubecolor = "0.5.1"
kube-score = "1.20.0"
kubeval = "0.16.1"
kyverno = "1.14.1"
pluto = "5.21.7"
"aqua:awslabs/eks-node-viewer" = "0.7.4"
"aqua:kubescape/kubescape" = "3.0.35"
## helm
helm-ct = "3.12.0"
helm-diff = "3.12.1"
helm-docs = "1.14.2"
## platform
amazon-ecr-credential-helper = "0.9.1"
## cost management
infracost = "0.10.41"
## Policy as Code
conftest = "0.61.0"
