[settings]
jobs = 20
experimental = true

[settings.npm]
bun = true

[tools]
"npm:czg" = "1.12.0"
"npm:gitmoji-cli" = "9.6.0"
"ubi:YiNNx/cmd-wrapped" = "0.4"
dyff = "1.10.1"
fzf = "0.65.2"
jqp = "0.7.0"
lefthook = "1.11.13"
"npm:@redocly/cli" = "1.34.3"
"npm:sql-formatter" = "15.6.2"
"npm:git-open" = "3.1.0"
"aqua:knqyf263/pet" = "1.0.1"
"go:github.com/hashicorp/hcl/v2/cmd/hclfmt" = "v2.24.0"
ls-lint = "2.3.1"

# AI
"npm:opencode-ai" = "1.1.11"
"pipx:mcpo" = "0.0.17"

# app
## TS
node = "24.9.0"
bun = "1.3.5"
"npm:@antfu/ni" = "28.0.0"
## go
gotestsum = "1.12.2"
"go:github.com/josharian/impl" = "1.4.0"
"go:github.com/fatih/gomodifytags" = "1.17.0"
golangci-lint = "2.1.6"
"go:github.com/cweill/gotests/..." = "1.6.0"

# infra
## cloud
awscli = "2.31.8"
aws-vault = "7.2.0"
granted = "0.38.0"
## container
hadolint = "2.12.0"
"asdf:kheino/asdf-skopeo" = "1.20.0"
"ubi:docker/docker-credential-helpers" = { version = "0.9.3", exe = "docker-credential-pass" }
## terraform
terraform-docs = "0.20.0"
terraform-ls = "0.38.1"
## kubernetes
kubectl = "1.34.1"
kubectx = "0.9.5"
kubens = "0.9.5"
kind = "0.29.0"
kubecolor = "0.5.1"
kube-score = "1.20.0"
kubeval = "0.16.1"
kyverno = "1.14.1"
pluto = "5.21.7"
"aqua:awslabs/eks-node-viewer" = "0.7.4"
"aqua:kubescape/kubescape" = "3.0.35"
## helm
helm = "3.19.0"
helm-ct = "3.12.0"
helm-diff = "3.12.1"
helm-docs = "1.14.2"
## platform
amazon-ecr-credential-helper = "0.9.1"
## cost management
infracost = "0.10.41"
## Policy as Code
conftest = "0.61.0"
## Security
### for mise verification
"go:github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier" = "v2.7.1"
